export const carBrands: { [key: string]: string[] } = {
    Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5'],
    BMW: ['Z3', 'E34', 'X5', 'X3', 'X7', 'Z4', 'E38', 'E65', 'F02', 'E32'],
    Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y'],
    Mercedes: ['C-Class', 'E-Class', 'S-Class', 'GLC', 'GLE', 'GLA', 'GLB', 'A-Class', 'CLA', 'G-Class'],
    Porsche: ['911', 'Cayenne', 'Panamera', 'Macan', 'Taycan', 'Boxster', 'Cayman', '718', '918 Spyder', '959'],
    AlfaRomeo: ['Giulia', 'Stelvio', '4C', 'Giulietta', 'Brera', 'GTV', 'Spider', 'SZ', 'RZ', 'Montreal'],
    AstonMartin: ['DB11', 'Vantage', 'DBS Superleggera', 'DBX', 'Rapide', 'Valhalla', 'Valkyrie', 'Virage', 'DB9', 'Vanquish'],
    Bentley: ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne', 'Brooklands', 'Azure', 'Arnage', 'Turbo R', 'Mark VI', 'S1'],
    Bugatti: [
        'Chiron',
        'Veyron',
        'Divo',
        'Centodieci',
        'La Voiture Noire',
        'EB110',
        'Type 41 Royale',
        'Type 57SC Atlantic',
        'Type 35',
        'Type 252',
    ],
    Ferrari: [
        'F8 Tributo',
        '488 GTB',
        '812 Superfast',
        'Roma',
        'SF90 Stradale',
        'Portofino',
        'GTC4Lusso',
        'Monza SP1',
        'Monza SP2',
        'LaFerrari',
    ],
    Jaguar: ['F-Type', 'XE', 'XF', 'XJ', 'E-PACE', 'F-PACE', 'I-PACE', 'XK', 'C-X75', 'SS 100'],
    Lamborghini: ['Aventador', 'Huracan', 'Urus', 'Sian FKP 37', 'Gallardo', 'Diablo', 'Countach', 'Miura', 'Murcielago', 'Veneno'],
    LandRover: [
        'Range Rover',
        'Range Rover Sport',
        'Range Rover Velar',
        'Range Rover Evoque',
        'Discovery',
        'Defender',
        'Discovery Sport',
        'Range Rover Classic',
        'Range Rover PHEV',
        'Freelander',
    ],
    Maserati: ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'GranCabrio', 'Spyder', 'Shamal', 'Bora', 'Khamsin', '3200 GT'],
};
